### ISSUE TITLE
not building on ubuntu 20.04

### ISSUE THREAD

**Issue by digitalsignalperson** [someone1/zfsbackup-go#538]
trying to build on an ubuntu 20.04 box (vagrant "generic/ubuntu2004") results in the following errors

```
vagrant@ubuntu2004:/vagrant$ go get github.com/someone1/zfsbackup-go
# golang.org/x/oauth2/google/internal/externalaccount
/home/vagrant/go/src/golang.org/x/oauth2/google/internal/externalaccount/executablecredsource.go:256:15: undefined: io.ReadAll
# golang.org/x/net/http2
/home/vagrant/go/src/golang.org/x/net/http2/transport.go:426:45: undefined: os.ErrDeadlineExceeded
```

**Comment by digitalsignalperson** [comment]
trying on arch linux

```
$ go get github.com/someone1/zfsbackup-go
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

so readme instructions deprecated

this builds without errors: `go install github.com/someone1/zfsbackup-go@latest`

**Comment by digitalsignalperson** [comment]
also using the latest version of go on ubuntu solves it

```
sudo add-apt-repository ppa:longsleep/golang-backports
sudo apt update
sudo apt install golang-go
go install github.com/someone1/zfsbackup-go@latest
```
